In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=sys.maxsize)

In [5]:
df = pd.read_csv('Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [93]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values
X[:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [94]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# labelencoder - provides a very efficient tool for encoding
# the levels of categorical features into numeric values. 
#X[:,2] entire gender column
labelencoder_gender = LabelEncoder()
X[:, 2] = labelencoder_gender.fit_transform(X[:, 2])
X[:5]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [95]:
from sklearn.compose import ColumnTransformer
# remainder - by default only the column transformed would be returned by 
# transformer,'passthrough' they will be unchanged, 'ohe' just a name of t-former
ct = ColumnTransformer([('ohe', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype = str) # float? working fine too
X = X[:, 1:]
X[:5]

array([['0.0', '0.0', '619', '0', '42', '2', '0.0', '1', '1', '1',
        '101348.88'],
       ['0.0', '1.0', '608', '0', '41', '1', '83807.86', '1', '0', '1',
        '112542.58'],
       ['0.0', '0.0', '502', '0', '42', '8', '159660.8', '3', '1', '0',
        '113931.57'],
       ['0.0', '0.0', '699', '0', '39', '1', '0.0', '2', '0', '0',
        '93826.63'],
       ['0.0', '1.0', '850', '0', '43', '2', '125510.82', '1', '1', '1',
        '79084.1']], dtype='<U9')

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                    test_size = 0.2, random_state = 0)

In [97]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [79]:
X_test[:3]

array([[ 1.75486502, -0.57369368, -0.55204276, -1.09168714, -0.36890377,
         1.04473698,  0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,
         1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, -1.09168714,  0.10961719,
        -1.031415  ,  0.42972196, -0.92159124,  0.64259497, -1.03227043,
         0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, -1.09168714,  0.30102557,
         1.04473698,  0.30858264, -0.92159124,  0.64259497,  0.9687384 ,
        -0.42478674]])

In [100]:
from tensorflow.keras.models import Sequential 
from keras.layers import Dense
# sequential allows to build an ANN as a sequence of layers
# dense allows to create fully conneted network
# kernel_initilaizer is used to initialize a weights in a network

#classifier = Sequential()
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier = Sequential([
    Dense(units = 11, kernel_initializer='uniform', activation='relu', input_dim=11),
    Dense(units = 11, kernel_initializer='uniform', activation='relu'),
    Dense(units = 1, kernel_initializer='uniform', activation='sigmoid')
])
classifier.compile(optimizer = 'adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [101]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)
# batch size = at a time it takes 10 rows 
# epochs = alogrithm run across the network

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7958
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4387 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4311 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4272 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4245 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4217 - accuracy: 0.8031
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4189 - accuracy: 0.8210
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4164 - accuracy: 0.8259
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4139 - accuracy: 0.8304
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4116 - accura

In [102]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 3ms/step


In [103]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1523   72]
 [ 213  192]]


0.8575

In [104]:
classifier.save('ann_model.h5')